import { FormEvent, useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import { api, createPatient, listAppointments, listPatients, me, register, login, Patient, User } from './api/client';
import './styles.css';

function Auth({ onDone }: { onDone: () => void }) { const [mode, setMode] = useState<'login'|'register'>('login'); const [form, setForm] = useState({ email:'', password:'', clinic_name:'', full_name:'' }); const [error, setError] = useState(''); const nav = useNavigate(); const submit = async (e: FormEvent) => { e.preventDefault(); setError(''); try { if(mode==='login') await login(form.email, form.password); else await register(form); onDone(); nav('/'); } catch { setError('Authentication failed. Check the details and try again.'); } }; return <main className="auth"><section className="card"><p className="eyebrow">DENTACARE</p><h1>{mode==='login'?'Welcome back':'Create your clinic'}</h1><form onSubmit={submit}>{mode==='register' && <><label>Clinic name<input required value={form.clinic_name} onChange={e=>setForm({...form,clinic_name:e.target.value})}/></label><label>Your name<input required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label></>}<label>Email<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Password<input type="password" required minLength={12} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{error && <p className="error">{error}</p>}<button type="submit">{mode==='login'?'Sign in':'Create account'}</button></form><button className="link" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'New clinic? Register':'Already registered? Sign in'}</button></section></main> }

function Layout({ user, children }: { user: User; children: React.ReactNode }) { return <div className="shell"><aside><p className="eyebrow">DENTACARE</p><h2>{user.full_name}</h2><span className="role">{user.role.replace('_',' ')}</span><nav><Link to="/">Overview</Link><Link to="/patients">Patients</Link><Link to="/appointments">Appointments</Link></nav><button className="link logout" onClick={()=>{localStorage.clear(); location.reload();}}>Sign out</button></aside><main className="content">{children}</main></div> }

function Patients() { const qc=useQueryClient(); const [search,setSearch]=useState(''); const [form,setForm]=useState({first_name:'',last_name:'',phone:'',email:'',notes:''}); const patients=useQuery({queryKey:['patients',search],queryFn:()=>listPatients(search)}); const create=useMutation({mutationFn:createPatient,onSuccess:()=>{qc.invalidateQueries({queryKey:['patients']});setForm({first_name:'',last_name:'',phone:'',email:'',notes:''})}}); return <><header><div><p className="eyebrow">PATIENT 360</p><h1>Patients</h1></div><input className="search" placeholder="Search patients" value={search} onChange={e=>setSearch(e.target.value)}/></header><section className="grid two"><div className="card"><h2>Add patient</h2><form onSubmit={e=>{e.preventDefault();create.mutate(form)}}><label>First name<input required value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/></label><label>Last name<input required value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button disabled={create.isPending}>Save patient</button></form></div><div className="card"><h2>Patient list</h2>{patients.isLoading?<p>Loading…</p>:patients.isError?<p className="error">Unable to load patients.</p>:patients.data?.length===0?<p className="muted">No patients found.</p>:<div className="list">{patients.data?.map((p:Patient)=><article key={p.id}><strong>{p.first_name} {p.last_name}</strong><span>{p.phone || p.email || 'No contact details'}</span></article>)}</div>}</div></section></> }

function Appointments() { const appointments=useQuery({queryKey:['appointments'],queryFn:listAppointments}); return <><header><div><p className="eyebrow">SCHEDULE</p><h1>Appointments</h1></div><Link className="button" to="/">Back to overview</Link></header><section className="card"><h2>Upcoming and recent appointments</h2>{appointments.isLoading?<p>Loading…</p>:appointments.data?.length===0?<p className="muted">No appointments scheduled.</p>:appointments.data?.map(a=><article className="appointment" key={a.id}><strong>{new Date(a.starts_at).toLocaleString()}</strong><span>{a.appointment_type} · {a.status}</span></article>)}</section></> }

function Home({user}:{user:User}) { const patients=useQuery({queryKey:['patients'],queryFn:()=>listPatients()}); const appointments=useQuery({queryKey:['appointments'],queryFn:listAppointments}); return <><header><div><p className="eyebrow">CLINIC OVERVIEW</p><h1>Good morning, {user.full_name.split(' ')[0]}</h1></div></header><section className="stats"><div className="card"><span>Patients</span><strong>{patients.data?.length ?? '—'}</strong></div><div className="card"><span>Appointments</span><strong>{appointments.data?.length ?? '—'}</strong></div><div className="card"><span>Clinic</span><strong className="small">{user.clinic_id.slice(0,8)}</strong></div></section><section className="card notice"><h2>Milestone ready</h2><p>Authentication, clinic isolation, patient records, rooms, and conflict-safe appointments are available. Treatment plans, inventory, odontograms, and periodontology are documented as upcoming modules.</p></section></> }

export default function App() { const [user,setUser]=useState<User|null>(null); const [loading,setLoading]=useState(true); useEffect(()=>{if(localStorage.getItem('access_token')) me().then(setUser).catch(()=>localStorage.clear()).finally(()=>setLoading(false)); else setLoading(false)},[]); if(loading) return <main className="auth"><p>Loading…</p></main>; if(!user) return <Auth onDone={()=>me().then(setUser)}/>; return <Layout user={user}><Routes><Route path="/" element={<Home user={user}/>}/><Route path="/patients" element={<Patients/>}/><Route path="/appointments" element={<Appointments/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes></Layout> }
