import { useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { createUnavailability, deleteUnavailability, getClinic, listRooms, listStaff, listUnavailability, listWorkingHours, replaceWorkingHours, Unavailability, WorkingHours } from './api/client';

const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
function clinicToUtc(value: string, timezone: string): string { const wall = new Date(`${value}:00Z`); const parts = new Intl.DateTimeFormat('en-US', { timeZone: timezone, year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hourCycle: 'h23' }).formatToParts(wall); const get = (type: string) => Number(parts.find(part => part.type === type)?.value); const represented = Date.UTC(get('year'), get('month') - 1, get('day'), get('hour'), get('minute'), get('second')); return new Date(wall.getTime() - (represented - wall.getTime())).toISOString(); }
function affectedMessage(items: Array<{ id: string; starts_at: string }>): string { return items.length ? `Existing appointments affected: ${items.map(item => `${item.id.slice(0, 8)} at ${new Date(item.starts_at).toLocaleString()}`).join(', ')}. Review or reschedule them.` : 'Availability saved.'; }
export function AvailabilitySettings() {
  const client = useQueryClient(); const clinic = useQuery({ queryKey: ['clinic'], queryFn: getClinic }); const hours = useQuery({ queryKey: ['working-hours'], queryFn: listWorkingHours }); const unavailability = useQuery({ queryKey: ['unavailability'], queryFn: listUnavailability }); const rooms = useQuery({ queryKey: ['rooms'], queryFn: listRooms }); const staff = useQuery({ queryKey: ['staff'], queryFn: listStaff }); const [rows, setRows] = useState<Array<Omit<WorkingHours, 'id'>>>([]); const [message, setMessage] = useState('');
  useEffect(() => { if (hours.data) setRows(hours.data.map(({ id, ...row }) => row)); }, [hours.data]);
  const saveHours = useMutation({ mutationFn: () => replaceWorkingHours(rows), onSuccess: result => { setMessage(affectedMessage(result.affected_appointments)); void client.invalidateQueries({ queryKey: ['working-hours'] }); }, onError: error => setMessage(error instanceof Error ? error.message : 'Unable to save working hours.') });
  const addRow = (day: number) => setRows(current => [...current, { day_of_week: day, start_time: '09:00:00', end_time: '17:00:00', is_active: true }]); const removeRow = (index: number) => setRows(current => current.filter((_, rowIndex) => rowIndex !== index)); const updateRow = (index: number, key: 'start_time' | 'end_time', value: string) => setRows(current => current.map((row, rowIndex) => rowIndex === index ? { ...row, [key]: `${value}:00`.slice(0, 8) } : row));
  const resources = useMemo(() => [...(rooms.data ?? []).map(room => ({ id: room.id, type: 'room', name: `Room · ${room.name}` })), ...(staff.data ?? []).filter(person => ['doctor', 'assistant'].includes(person.role)).map(person => ({ id: person.id, type: person.role, name: `${person.role} · ${person.full_name}` }))], [rooms.data, staff.data]); const [resource, setResource] = useState(''); const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const [reason, setReason] = useState('');
  const addBlock = useMutation({ mutationFn: () => { const selected = resources.find(item => item.id === resource); if (!selected || !clinic.data) throw new Error('Select a resource and clinic times.'); return createUnavailability({ resource_type: selected.type, resource_id: selected.id, starts_at: clinicToUtc(start, clinic.data.timezone), ends_at: clinicToUtc(end, clinic.data.timezone), reason: reason || undefined }); }, onSuccess: result => { setMessage(affectedMessage(result.affected_appointments)); setStart(''); setEnd(''); setReason(''); void client.invalidateQueries({ queryKey: ['unavailability'] }); }, onError: error => setMessage(error instanceof Error ? error.message : 'Unable to block availability.') }); const removeBlock = useMutation({ mutationFn: deleteUnavailability, onSuccess: () => { setMessage('Unavailability removed.'); void client.invalidateQueries({ queryKey: ['unavailability'] }); } });
  return <section className="card"><h2>Working hours and availability</h2><p className="muted">Clinic timezone: {clinic.data?.timezone ?? 'loading…'}. An entirely empty schedule is <strong>unconfigured</strong> and permits booking. Once any day is configured, a day with no row is explicitly <strong>closed</strong>.</p>{message && <p className="notice-text" role="alert">{message}</p>}<div className="list">{DAYS.map((day, dayIndex) => <article className="list-row" key={day}><span><strong>{day}</strong>{rows.filter(row => row.day_of_week === dayIndex).length === 0 && <small className="muted"> {rows.length ? 'Closed' : 'Unconfigured'}</small>}{rows.filter(row => row.day_of_week === dayIndex).map((row, index) => { const actualIndex = rows.indexOf(row); return <span className="availability-row" key={`${day}-${actualIndex}`}><input aria-label={`${day} start`} type="time" value={row.start_time.slice(0, 5)} onChange={event => updateRow(actualIndex, 'start_time', event.target.value)} />–<input aria-label={`${day} end`} type="time" value={row.end_time.slice(0, 5)} onChange={event => updateRow(actualIndex, 'end_time', event.target.value)} /><button type="button" className="secondary" onClick={() => removeRow(actualIndex)}>Remove</button></span>; })}</span><button type="button" className="secondary" onClick={() => addRow(dayIndex)}>Add hours</button></article>)}</div><button type="button" onClick={() => saveHours.mutate()} disabled={saveHours.isPending}>Save working hours</button><hr /><h3>Block a doctor, assistant, or room</h3><p className="muted">Times are entered in the clinic timezone and existing overlapping appointments are listed before you review them.</p><div className="grid two"><label>Resource<select value={resource} onChange={event => setResource(event.target.value)}><option value="">Select resource</option>{resources.map(item => <option key={`${item.type}-${item.id}`} value={item.id}>{item.name}</option>)}</select></label><label>Reason<input value={reason} onChange={event => setReason(event.target.value)} /></label><label>Starts<input type="datetime-local" value={start} onChange={event => setStart(event.target.value)} /></label><label>Ends<input type="datetime-local" value={end} onChange={event => setEnd(event.target.value)} /></label></div><button type="button" onClick={() => addBlock.mutate()} disabled={addBlock.isPending || !resource || !start || !end}>Block availability</button><div className="list">{(unavailability.data ?? []).map((item: Unavailability) => <article className="list-row" key={item.id}><span>{item.resource_type} · {item.reason || 'Unavailable'}<br /><small>{new Date(item.starts_at).toLocaleString()} – {new Date(item.ends_at).toLocaleString()}</small></span><button type="button" className="secondary" onClick={() => removeBlock.mutate(item.id)}>Remove</button></article>)}</div></section>;
}
